tag 'rpm-0_5_0-noarch' created by fw-revision-svn

diff --git a/bin/fw-package b/bin/fw-package
--- a/bin/fw-package
+++ b/bin/fw-package
@@ -61,10 +61,14 @@ check_for_tag () \
     fw_exec "revision/$revision/check-for-tag" "$@" --tag "$tag" || {
       echo "fw-package: warning: tag '$tag' already exists" 1>&2
       echo "fw-package: warning: probably this package has already been released" 1>&2
-      test "$release" != yes || {
-        echo "fw-package: error: cannot release package in this state" 1>&2
-        fatal "fw-package"
-      }
+      if test -z "$FW_SKIP_TAG" ; then
+        test "$release" != yes || {
+          echo "fw-package: error: cannot release package in this state" 1>&2
+          fatal "fw-package"
+        }
+      else
+        echo "fw-package: allowing release since FW_SKIP_TAG is set" 1>&2
+      fi
     }
   }
 
@@ -179,7 +183,15 @@ if test "x$source_install_only" = x
     
     test ! -d fw-pkgtmp || rm -rf fw-pkgtmp || fatal "fw-package"
     
-    make_tag "$@" --tag "$tag"
+    if test -z "$FW_SKIP_TAG" ; then
+      make_tag "$@" --tag "$tag"
+    else
+      echo "fw-package: skip making tag since FW_SKIP_TAG is set" 1>&2
+    fi
     
-    release_package "$@" --outdir "$outdir"
+    if test -z "$FW_SKIP_RELEASE" ; then
+      release_package "$@" --outdir "$outdir"
+    else
+      echo "fw-package: skip release since FW_SKIP_RELEASE is set" 1>&2
+    fi
   fi
diff --git a/fw/revision/svn/check-for-tag b/fw/revision/svn/check-for-tag
--- a/fw/revision/svn/check-for-tag
+++ b/fw/revision/svn/check-for-tag
@@ -14,7 +14,7 @@ test -f "${FW_ROOT}/share/fw/sh/fw-find.sh" && fws="${FW_ROOT}/share/fw/sh/fw-fi
 test -f "fw/sh/fw-find.sh" && fws="fw/sh/fw-find.sh"
 test -f "fw.local/sh/fw-find.sh" && fws="fw.local/sh/fw-find.sh"
 test ! -z "$fws" || {
-  echo "revision/cvs/check-for-tag: fatal: can't locate fw-find.sh" 1>&2
+  echo "revision/svn/check-for-tag: fatal: can't locate fw-find.sh" 1>&2
   exit 1
 }
 
@@ -24,17 +24,17 @@ test ! -z "$fws" || {
 #                              routines                               
 #---------------------------------------------------------------------
 
-fw_source "revision/cvs/check-for-tag" "sh/fatal.sh"
-fw_source "revision/cvs/check-for-tag" "sh/parse-args.sh"
-fw_source "revision/cvs/check-for-tag" "sh/validate-args.sh"
+fw_source "revision/svn/check-for-tag" "sh/fatal.sh"
+fw_source "revision/svn/check-for-tag" "sh/parse-args.sh"
+fw_source "revision/svn/check-for-tag" "sh/validate-args.sh"
 
 #---------------------------------------------------------------------
 #                                main                                 
 #---------------------------------------------------------------------
 
-parse_args "revision/cvs/check-for-tag" "$@"
+parse_args "revision/svn/check-for-tag" "$@"
 
-validate_args "revision/cvs/check-for-tag" "tag" ""
+validate_args "revision/svn/check-for-tag" "tag" ""
 
 eval `fw-exec "template/$template/load-config"`
 
